### ISSUE TITLE
Schließende PHP Tag

### ISSUE THREAD

**Issue by tabacha** [bensteffen/adfc-t30-api#11]
Ich würde die PHP Tags nicht schließen: 

http://blog.ebene7.com/2010/03/08/das-schliessende-php-tag-am-ende-einer-datei-und-die-sache-mit-der-stecknadel-im-heuhaufen/

**Comment by bensteffen** [comment]
Ich hatte tatsächlich schon Probleme mit White-Spaces hinter dem schließenden PHP-Tag. Auf die Idee sie einfach wegzulassen bin ich gar nicht gekommen.

**Comment by bensteffen** [comment]
Erledigt
