### ISSUE TITLE
Zu ADFC-Hamburg übernehmen?

### ISSUE THREAD

**Issue by tabacha** [bensteffen/adfc-t30-api#2]
Ich schlage vor, ich forke das Projekt bei https://github.com/ADFC-Hamburg und wir entwickeln dort weiter?

**Comment by tabacha** [comment]
Ich kann hier die Issues nicht verwalten, also z.B. Tags vergeben etc.

**Comment by bensteffen** [comment]
Ja, klingt sinnvoll

**Comment by tabacha** [comment]
Hab das bei ADFC geforkt
