### ISSUE TITLE
Wie weiter mit dem vendor Verzeichnis?

### ISSUE THREAD

**Issue by tabacha** [bensteffen/adfc-t30-api#3]
Moin,

der Sinn von Composer ist ja, dass man die Projekte weiter splitet und so z.B. Firebase aktualisieren kann, wenn dort ein Bug gefixt oder eine Sicherheitslücke auftaucht.

### Vorschlag: Composer benutzen

Mein Vorschlag wäre, du veröffentlichst die  Repros: 

   "bensteffen/bs-php-utils": "^1.0",
   "bensteffen/flexapi": "^1.0",
   "bensteffen/php-gps": "^1.0"

und überlegst dir, ob es Sinn macht, das wir diese auch unter ADFC-Hamburg hosten und von dort via Composer einbinden oder ob sie in deinem Github-Repo bleiben sollen und wir dort Mitarbeiten.

Das Verzeichnis vendor sollten wir dann leer machen, das wird ja via Composer erstellt  und wir dann auch die Git commits dazu sauber haben, ein Update auf z.B. Firebase Version 5.1 sieht dann auch in der Git-History so aus:

  ALT: "firebase/php-jwt": "^5.0",
  NEU: "firebase/php-jwt": "^5.1",

### Alternative: Die "bensteffen" repros nicht via Composer laden 

Alternativ könnten wir die "bensteffen" repros nicht via Composer laden und (fände ich sauberer) in ein anderes Verzeichnis als vendor legen, dann würden wir, wenn es dort Änderungen gibt, diese einfach bearbeiten.

**Comment by bensteffen** [comment]
Wir machen so wie es gedacht mit Composer. Ich hatte das Vendor-Verzeichnis damals in der ADFC-Zentrale nur mal schnell mit hochgeladen, damit Ihr was sehen könnt, weil die Repos da noch private waren. Ich hab jetzt alle benötigten Repos von mir (flexapi und php-utils) public gesetzt.
